### ISSUE TITLE
TaxonRepository decoration type error

### ISSUE THREAD

**Issue by QuentinDess** [BitBagCommerce/SyliusVueStorefront2Plugin#96]
Hello ✋ 
I face an issue with a new setup of Sylius and this plugin
I follow every step of the documentation , and my sylius/sylius version is 1.11.15 
The issue is located with this config 
```
sylius_taxonomy:
    resources:
        taxon:
            classes:
                model: App\Entity\Taxonomy\Taxon
                repository: BitBag\SyliusVueStorefront2Plugin\Doctrine\Repository\TaxonRepository
            translation:
                classes:
                    model: App\Entity\Taxonomy\TaxonTranslation
```
When i go to any kind of url i have this error
```
BitBag\SyliusVueStorefront2Plugin\Doctrine\Repository\TaxonRepository::__construct(): Argument #1 ($decoratedRepository) 
must be of type Sylius\Component\Taxonomy\Repository\TaxonRepositoryInterface, 

ContainerQSsNVi1\EntityManager_9a5be93 given, called in /backend/var/cache/dev/ContainerQSsNVi1/getSylius_Repository_TaxonService.php on line 32
```
Any idea about this ?
I try to decorate manually the file but still the same . 
I a m using symfony  5.4
Thanks
